from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import os
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="TeraLeads AI Service", version="1.0.0")

# Enable CORS so backend can call this service
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this to your backend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request/Response models
class GenerateRequest(BaseModel):
    message: str
    patientContext: Optional[dict] = None


class GenerateResponse(BaseModel):
    response: str


# Mock AI response function (fallback if no real AI is configured)
def mock_ai_response(message: str, patient_context: Optional[dict] = None) -> str:
    """Simple mock response for testing"""
    context_info = ""
    if patient_context:
        name = patient_context.get("name", "patient")
        context_info = f" (Patient: {name})"
    
    return f"This is a mock dental assistant response to: '{message}'{context_info}. In production, this would be generated by an AI model."


# Real AI function (if OpenAI API key is set)
def generate_ai_response(message: str, patient_context: Optional[dict] = None) -> str:
    """Generate AI response using OpenAI API"""
    try:
        from openai import OpenAI
        
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            # Fallback to mock if no API key
            return mock_ai_response(message, patient_context)
        
        client = OpenAI(api_key=api_key)
        
        # Build context-aware prompt
        system_prompt = """You are a helpful dental assistant. Provide professional and helpful responses to patient questions about dental care, appointments, and oral health."""
        
        user_prompt = f"Patient question: {message}"
        
        if patient_context:
            name = patient_context.get("name", "")
            if name:
                user_prompt += f"\n\nPatient name: {name}"
        
        # Call OpenAI API
        response = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-3.5-turbo"),
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            max_tokens=200,
            temperature=0.7
        )
        
        return response.choices[0].message.content.strip()
    
    except Exception as e:
        # If OpenAI fails, fallback to mock
        print(f"OpenAI error: {e}")
        return mock_ai_response(message, patient_context)


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "ok"}


@app.post("/generate", response_model=GenerateResponse)
async def generate_response(request: GenerateRequest):
    """
    Generate AI response to a patient message.
    
    - If OPENAI_API_KEY is set, uses OpenAI
    - Otherwise, returns a mock response
    """
    try:
        response_text = generate_ai_response(
            request.message,
            request.patientContext
        )
        
        return GenerateResponse(response=response_text)
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate response: {str(e)}")